tab_spaces = 4
error_on_unformatted = true
format_strings = true
edition = "2024"
max_width = 120
imports_granularity = "Module"
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
style_edition = "2024"
unstable_features = true
wrap_comments = true
comment_width = 125
