[package]
name = "typlate"
version = "0.1.0"
edition = "2024"

[features]
default = ["derive"]
derive = []

[dependencies]
serde = { version = "1.0", features = ["derive"] }
typlate_derive = { path = "../typlate_derive" }

[dev-dependencies]
serde_json = "1.0"
